version: '3'
services:
  notebook:
    #image: jupyter/base-notebook
    build: .
    user: root
    ports:
    - 7474:8888
    - 7575:8050    
    volumes:
    - ${PWD}/.:/home/jovyan/
    environment:
    - NB_UID=1006
    - GRANT_SUDO=yes
    command: ['start-notebook.sh', "--NotebookApp.password='sha1:73270fcb150b:17fd74a7fca967917116e81b9581b6182634c8bb'"]
